name = "Nate"
uuid = "cf6aba5e-4589-434e-affe-f0aa648ef8c6"
repo = "https://github.com/nateybear/JuliaTools.git"

[packages]
60ba8f4c-593d-46aa-8758-bd97a13e7b03 = { name = "Snakemake", path = "S/Snakemake" }
