name = "Here"
uuid = "6944d17e-2d8e-48b7-9f52-ed9d5a0ad34e"
version = "0.1.0"
authors = ["Nathan Gardner Hattersley <nate.hattersley@gmail.com>"]

[deps]
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"

[compat]
Glob = "1.3.1"
